# Generated by Django 2.1 on 2018-09-03 19:34

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='نام دسته')),
                ('Slug', models.SlugField(max_length=200, unique=True, verbose_name='نشانک دسته')),
                ('Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CHILDS', to='blog.Category', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته ها',
                'ordering': ['Name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentTime', models.DateTimeField(auto_created=True, verbose_name='زمان نظر دادن')),
                ('CommentStatus', models.CharField(choices=[('A', 'تایید شده'), ('N', 'تایید نشده'), ('D', 'رد شده')], default='N', max_length=1, verbose_name='وضعیت نظر')),
                ('CommenterName', models.CharField(default='کاربر ناشناس', max_length=200, verbose_name='نام نظردهنده')),
                ('CommentBody', models.TextField(max_length=1000, verbose_name='متن نظر')),
                ('CommentTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='REPLIES', to='blog.Comment')),
                ('CommenterUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر نظردهنده')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرها',
                'ordering': ['-CommentTime'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, verbose_name='عنوان پست')),
                ('Slug', models.SlugField(unique_for_date='PublishTime', verbose_name='نشانک پست')),
                ('Body', models.TextField(verbose_name='متن پست')),
                ('PublishTime', models.DateTimeField(verbose_name='تاریخ انتشار')),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('LastEditTime', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(choices=[('P', 'منتشر شده'), ('D', 'پیشنویس')], default='d', max_length=1, verbose_name='وضعیت انتشار')),
                ('Image', models.ImageField(blank=True, null=True, upload_to=blog.models.post_photo_path, verbose_name='تصویر پست')),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده پست')),
                ('Categories', models.ManyToManyField(blank=True, null=True, related_name='POSTS', to='blog.Category', verbose_name='دسته ها')),
                ('Tags', taggit.managers.TaggableManager(blank=True, help_text='تگ ها را با علامت کاما جدا کنید.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='برچسب های پست')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ['-PublishTime'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, verbose_name='عنوان اسلاید')),
                ('Body', models.TextField(verbose_name='متن اسلاید')),
                ('PublishTime', models.DateTimeField(verbose_name='تاریخ انتشار')),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('LastEditTime', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(choices=[('P', 'منتشر شده'), ('D', 'پیشنویس')], default='d', max_length=1, verbose_name='وضعیت انتشار')),
                ('Image', models.ImageField(upload_to=blog.models.slider_photo_path, verbose_name='تصویر اسلاید')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلاید ها',
                'ordering': ['-PublishTime'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='PostTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='COMMENTS', to='blog.Post', verbose_name='پست مورد نظر'),
        ),
    ]
