# Generated by Django 2.1 on 2018-08-23 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=180, verbose_name='عنوان پست')),
                ('Slug', models.SlugField(unique_for_date=True, verbose_name='نشانک')),
                ('Body', models.TextField(max_length=2000, verbose_name='متن پست')),
                ('PublishTime', models.DateTimeField(verbose_name='تاریخ انتشار')),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('LastEditTime', models.DateTimeField(auto_now=True)),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AUTHOR', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده پست')),
            ],
        ),
    ]
