# Generated by Django 2.1 on 2018-08-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Slug',
            field=models.SlugField(unique_for_date='PublishTime', verbose_name='نشانک'),
        ),
    ]
