# Generated by Django 2.1 on 2018-09-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='slider',
            table='slider',
        ),
    ]
