# Generated by Django 2.1 on 2018-08-23 04:49

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('blog', '0002_auto_20180823_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='تگ ها را با علامت کاما جدا کنید.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='برچسب های پست'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Slug',
            field=models.SlugField(unique_for_date='PublishTime', verbose_name='نشانک پست'),
        ),
    ]
