# Generated by Django 2.1.1 on 2018-09-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180904_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='CommenterEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
