# Generated by Django 2.1.1 on 2018-09-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_commenteremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Categories',
            field=models.ManyToManyField(blank=True, related_name='POSTS', to='blog.Category', verbose_name='دسته ها'),
        ),
    ]
