# Generated by Django 2.1 on 2018-08-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180823_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['PublishTime'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.AddField(
            model_name='post',
            name='Status',
            field=models.CharField(choices=[('P', 'منتشر شده'), ('D', 'پیشنویس')], default='d', max_length=1, verbose_name='وضعیت انتشار'),
        ),
    ]
