# Generated by Django 2.1 on 2018-08-23 22:13

from django.db import migrations
import django.db.models.manager
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180823_0933'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('jobject', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='PublishTime',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ انتشار'),
        ),
    ]
