# Generated by Django 2.1 on 2018-08-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180824_0243'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='PublishTime',
            field=models.DateTimeField(verbose_name='تاریخ انتشار'),
        ),
    ]
