# Generated by Django 2.1 on 2018-08-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180824_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.ImageField(height_field=300, null=True, upload_to='user_directory_path', verbose_name='تصویر پست', width_field=1000),
        ),
    ]
