# Generated by Django 2.1 on 2018-08-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180824_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='CommentStatus',
            field=models.CharField(choices=[('A', 'تایید شده'), ('N', 'تایید نشده'), ('D', 'رد شده')], default='N', max_length=1, verbose_name='وضعیت نظر'),
        ),
    ]
