# Generated by Django 2.1 on 2018-08-26 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_commentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='CommentTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='REPLIES', to='blog.Comment'),
        ),
    ]
