# Generated by Django 2.1 on 2018-08-26 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_commentto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='نام دسته')),
                ('Slug', models.SlugField(max_length=200, unique=True, verbose_name='نشانک دسته')),
                ('Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CHILDS', to='blog.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='Title',
            field=models.CharField(max_length=200, verbose_name='عنوان پست'),
        ),
        migrations.AddField(
            model_name='post',
            name='Categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='POSTS', to='blog.Category'),
        ),
    ]
